/*
 * errors.h
 *
 * Copyright (c) 2016-2019 Tim <and-joy@qq.com>
 * All rights reserved.
 */

#ifndef AWE_ERRORS_H_
#define AWE_ERRORS_H_

enum{
	AWE_OK		= 0,
	AWE_NOERROR	= 0,
	AWE_UNKNOWN_ERROR		= (-2147483647-1), // INT32_MIN value
	AWE_NO_MEMORY			= -12, //-ENOMEM,
	AWE_INVALID_OPERATION	= -38, //-ENOSYS,
	AWE_BAD_VALUE			= -22, //-EINVAL,
	AWE_BAD_TYPE			= (AWE_UNKNOWN_ERROR + 1),
	AWE_BAD_PARAM			= (AWE_UNKNOWN_ERROR + 2),
	AWE_NAME_NOT_FOUND		= -2, //-ENOENT,
	AWE_PERMISSION_DENIED	= -1, //-EPERM,
	AWE_NO_INIT				= -19, //-ENODEV,
	AWE_ALREADY_EXISTS		= -17, //-EEXIST,
	AWE_DEAD_OBJECT			= -32, //-EPIPE,
	AWE_FAILED_TRANSACTION	= (AWE_UNKNOWN_ERROR + 3),
	AWE_JPARKS_BROKE_IT		= -32, //-EPIPE,
	AWE_EBUSY				= -16, //-EBUSY
	AWE_TIMEDOUT			= -110, //-ETIMEDOUT
	AWE_EAGAIN				= -11, //-EAGAIN
	AWE_EOF					= (AWE_UNKNOWN_ERROR + 4),
};

#define AWE_CONN_NETUNREACH		101 //ENETUNREACH
#define AWE_CONN_HOSTUNREACH	103 //EHOSTUNREACH
#define AWE_CONN_TIMEDOUT		110 //ETIMEDOUT
#define AWE_CONN_REFUSED		111 //ECONNREFUSED
#define AWE_CONN_EINPROGRESS	115	//EINPROGRESS

#endif /* AWE_ERRNO_H_ */
